services:
  hammertime-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hammertime-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STATIC_API_KEY=${STATIC_API_KEY:-STATIC_KEY_123}
      - PORT=8080
      - DB_PATH=/app/data/usage.db
    volumes:
      - ./data:/app/data
    networks:
      - hammertime-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: hammertime-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - hammertime-api
    networks:
      - hammertime-network
    profiles:
      - production

networks:
  hammertime-network:
    driver: bridge

volumes:
  hammertime-data:
    driver: local 